#!/usr/bin/env bash
#### Smartpad Specific Tweaks for armbian images
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/KwadFan
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap


# Set CPU governor to powersave
echo_green "Set CPU governor powersave..."
  for CPU in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
 echo powersave | sudo tee "${CPU}";
 done
echo_green "Set CPU governor powersave...(DONE)"