#!/usr/bin/env bash

#### Sonar - A WiFi Keepalive daemon
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2022
#### https://github.com/mainsail-crew/sonar
####
#### This File is distributed under GPLv3
####

# shellcheck enable=requires-variable-braces

# Error handling
set -Ee

# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

mkdir -p /tmp
chmod 1777 /tmp


# Module only Variables
SR_BUILD_INSTALL_SH="/home/${BASE_USER}/sonar/tools/install.sh"
SR_BUILD_PACKAGE_FILE="/tmp/sr_packages.lst"

echo_green "Installing sonar ..."

## Force apt update
apt-get update
## Make sure 'git' is installed!
check_install_pkgs git

## Step 1: Move to Home Dir as WorkingDirectoy
pushd "/home/${BASE_USER}" &> /dev/null || exit 1

## Step 2: clone sonar repo
echo_green "Clone sonar repository ..."
gitclone SONAR_REPO sonar

## Step 3-5: Set SONAR_DEPS manually (bypass dynamic detection)
echo_green "Manually defining SONAR_DEPS ..."
SONAR_DEPS="network-manager wireless-tools iw ethtool curl net-tools"


## Step 6: Install packages
echo_green "Install sonar dependencies ..."
# shellcheck disable=SC2086
# disabled because we need 'wordsplitting'
check_install_pkgs ${SONAR_DEPS}

## Step 7: Move to sonar as working directory
pushd "/home/${BASE_USER}/sonar" &> /dev/null || exit 1

## Step 8: Run sonar install routine
echo_green "Launch sonar install routine ..."
ls -la /home/${BASE_USER}/sonar
cat /home/${BASE_USER}/sonar/tools/install.sh || echo ">> install.sh introuvable"
make install || { echo_red "Sonar install failed"; exit 1; }


## Step 9: Leave sonar
popd &> /dev/null || exit 1

## Step 10: clean packages.lst file
rm -f "${SR_BUILD_PACKAGE_FILE}"

## Step 11: leave home dir
popd &> /dev/null || exit 1

## Step 12:
echo_green "Enable sonar.service ..."
systemctl_if_exists enable sonar.service

## Finish
echo_green "Installing sonar ... DONE!"