#!/usr/bin/env bash
#### Smartpad Specific Tweaks for armbian images
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/KwadFan
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

#install docker
pushd "/home/${BASE_USER}" &>/dev/null
curl -sSL https://get.docker.com | sh
sudo usermod -aG docker ${USER}
sudo apt install libffi-dev libssl-dev python3-dev
sudo apt install python3 python3-pip
sudo pip3 install docker-compose
sudo systemctl enable docker
mkdir docker
cd docker
mkdir homeAssistant
cd homeAssistant
sudo docker-compose up -d
