#!/usr/bin/env bash
# Shebang pour une meilleure détection du fichier
# Voir https://www.shellcheck.net/wiki/SC2155 pour les bonnes pratiques

# URL de téléchargement de base
DOWNLOAD_BASE_URL="https://github.com/Yumi-Lab/SmartPi-armbian/releases/latest/download"

# Utilisateur de base
BASE_ADD_USER="yes"
BASE_USER="pi"
BASE_USER_PASSWORD="yumi"

# Paramètres pour SBC non-RPI
BASE_DISTRO="armbian"
BASE_IMAGE_RASPBIAN="no"

# Redimensionnement de la partition
BASE_ROOT_PARTITION="2"
BASE_IMAGE_ENLARGEROOT=2500
BASE_IMAGE_RESIZEROOT=600

# Point de montage de la partition de démarrage
BASE_BOOT_MOUNT_PATH="/boot/"

# Compression (inutile car le workflow gère déjà la compression)
BASE_RELEASE_COMPRESS=no

# Définition des modules
MODULES="base,pkgupgrade,udev_fix,armbian(armbian_net,yumios,klipper,is_req_preinstall,moonraker,mainsail,timelapse,crowsnest,sonar)"

# Export des variables
export DOWNLOAD_BASE_URL
export BASE_ADD_USER
export BASE_USER
export BASE_USER_PASSWORD
export BASE_DISTRO
export BASE_IMAGE_RASPBIAN
export BASE_ROOT_PARTITION
export BASE_IMAGE_ENLARGEROOT
export BASE_IMAGE_RESIZEROOT
export BASE_BOOT_MOUNT_PATH
export BASE_RELEASE_COMPRESS
export MODULES

# Débogage pour vérifier MODULES
echo "MODULES=${MODULES}"

# Vérification de l'exportation des variables
if [[ -z "${DOWNLOAD_BASE_URL}" || -z "${BASE_USER}" || -z "${MODULES}" ]]; then
    echo "Erreur : Une ou plusieurs variables nécessaires ne sont pas définies."
    exit 1
fi

echo "Script exécuté avec succès."
