#!/usr/bin/env bash
# Shebang pour une meilleure détection du fichier
# shellcheck enable=require-variable-braces
# shellcheck disable=SC2034

# Source de l'image
DOWNLOAD_BASE_URL="https://github.com/Yumi-Lab/SmartPi-armbian/releases/latest/download"
DOWNLOAD_URL_CHECKSUM="${DOWNLOAD_BASE_URL}/Yumi-smartpad-bookworm-server.img.xz.sha256"
DOWNLOAD_URL_IMAGE="${DOWNLOAD_BASE_URL}/Yumi-smartpad-bookworm-server.img.xz"

# Paramètres pour redimensionner l'image
BASE_IMAGE_ENLARGEROOT=6000

# Définition des modules avec structure corrigée
ARMBIAN_MODULES=""

# Vérification de la syntaxe des modules
MODULES="base(pkgupgrade,udev_fix,armbian(armbian_net,yumios,klipper,is_req_preinstall,moonraker,mainsail,timelapse,klipperscreen,crowsnest,sonar,smartpad,usb-automount,tmc-autotune,cpu_governor))"

# Export des variables
export BASE_ARCH
export DOWNLOAD_URL_CHECKSUM
export DOWNLOAD_URL_IMAGE
export BASE_IMAGE_ENLARGEROOT
export MODULES

# Débogage pour vérifier MODULES
echo "MODULES=${MODULES}"
