#!/usr/bin/env bash
# Shebang for better file detection
#### Smartpad Specific Tweaks for Yumi SmartPad images
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/KwadFan
####
#### This File is distributed under GPLv3
####

# shellcheck disable=all

[[ -n "$SMARTPAD_GIT_TMC_AUTOTUNE" ]] || SMARTPAD_GIT_TMC_AUTOTUNE="https://github.com/Maxime3d77/klipper_tmc_autotune.git"
