#!/usr/bin/env bash
#### Smartpad Specific Tweaks for armbian images
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/KwadFan
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

#Install TMC AUTOTUNE for GCODES
echo_green "Install TMC Autotune..."
pushd "/home/${BASE_USER}" &>/dev/null
echo_green "Install TMC Autotune git clone..."
sudo -u "${BASE_USER}" git clone https://github.com/Yumi-Lab/klipper_tmc_autotune
pushd "/home/${BASE_USER}/klipper_tmc_autotune" &> /dev/null || exit 1
echo_green "Install TMC Autotune launch script..."
KS_BUILD_INSTALL_SH="/home/${BASE_USER}/klipper_tmc_autotune/Install_tmc_autotune.sh"
sudo -u "${BASE_USER}" "${KS_BUILD_INSTALL_SH}"

echo_green "Update Moonraker TMC Autotune..."
cat << EOF | sudo tee -a /home/pi/printer_data/config/moonraker.conf > /dev/null

# TMC Autotune
[update_manager klipper_tmc_autotune]
type: git_repo
channel: dev
path: ~/klipper_tmc_autotune
origin: https://github.com/andrewmcgr/klipper_tmc_autotune
managed_services: klipper
primary_branch: main
install_script: install.sh

EOF
echo_green "Install TMC Autotune... [DONE]"
