#!/usr/bin/env bash
#### Smartpad Specific Tweaks for armbian images
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/KwadFan
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

# Install TMC AUTOTUNE for GCODES
echo_green "Install TMC Autotune..."
pushd "/home/pi" &>/dev/null
echo_green "Install TMC Autotune git clone..."
sudo git clone https://github.com/Yumi-Lab/klipper_tmc_autotune
pushd "/home/pi/klipper_tmc_autotune" &> /dev/null || exit 1
echo_green "Install TMC Autotune launch script..."
sudo chmod +x /home/pi/klipper_tmc_autotune/Install_tmc_autotune.sh
sudo ./home/pi/klipper_tmc_autotune/Install_tmc_autotune.sh

echo_green "Update Moonraker TMC Autotune..."
cat << EOF | sudo tee -a /home/pi/printer_data/config/tmc_autotune.cfg > /dev/null

# TMC Autotune
[update_manager klipper_tmc_autotune]
type: git_repo
channel: dev
path: ~/klipper_tmc_autotune
origin: https://github.com/andrewmcgr/klipper_tmc_autotune
managed_services: klipper
primary_branch: main
install_script: install.sh

EOF

# Add the line [include tmc_autotune.cfg] to the beginning of moonraker.conf
echo_green "Adding [include tmc_autotune.cfg] to /home/pi/printer_data/config/moonraker.conf..."
sudo sed -i '1i [include tmc_autotune.cfg]' /home/pi/printer_data/config/moonraker.conf

echo_green "Install TMC Autotune... [DONE]"

